    
language: python
python:
  - "3.6"
  
services:
  - docker

before_install:
  - sudo apt-get install -y tor
addons:
  apt:
    update: true  

install:
  - pip3 install -U PySocks tqdm
  - pip3 install -U git+https://github.com/OrganicIrradiation/scholarly.git
  - python3 fetch_pubs.py
  - docker build -t ipeirotis/scholar_update .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push ipeirotis/scholar_update
