# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 0 * * *"
    
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Cloud Functions Deploy
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        # Name of the Cloud Function.
        name: scholar-update
        # ID of the project in which to deploy the Cloud Function.
        project_id: scholarapi
        # Name of a function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified.
        entry_point: update_scholar_profile 
        # Runtime to use for the function.
        runtime: python38
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    

        
    - name: Fetch latest statistics for Panos
      run: |
        python3 fetch_pubs.py ipeirotis
    - name: Fetch latest statistics for Foster
      run: |
        python3 fetch_pubs.py "foster provost"
    - name: Upload to Google Storage Bucket
      run: |
        python3 upload_to_google_storage.py
