# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y tor
        python3 -m pip install --upgrade pip
        pip3 install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip3 install git+https://github.com/OrganicIrradiation/scholarly.git
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Decrypt Google credentials file
      run: ./decrypt_secret.sh
      env:
        GPG_PASSWORD:  ${{ secrets.GPG_PASSWORD }} 
    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/google-credentials-scholarAPI.json        
    - name: Fetch latest statistics for Panos
      run: |
        python3 fetch_pubs.py ipeirotis
    - name: Fetch latest statistics for Foster
      run: |
        python3 fetch_pubs.py provost
    - name: Upload to Google Storage Bucket
      run: |
        python3 upload_to_google_storage.py
